### ISSUE TITLE
Limited reading performance due to strange `delay(40)` in code

### ISSUE THREAD

**Issue by walchko** [adafruit/Adafruit_BMP3XX#13]
- Arduino board: PyQT
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.13

Thanks for all you do, you really do make great hardware/software!

I am trying to read the pressure sensor at ~200Hz with some other sensors and set it as:

```c++
if (!bmp.begin_I2C()) {
        while (1){
            Serial.println("BMP3 NOT Found!");
            delay(1000);
        }
    }
    bmp.setIIRFilterCoeff(BMP3_IIR_FILTER_COEFF_3);
    bmp.setOutputDataRate(BMP3_ODR_200_HZ);
```

However, when I execute `bmp.performReading()`, the performance is no where near ~200Hz unless I comment this performRead out. Looking at this function in github [here](https://github.com/adafruit/Adafruit_BMP3XX/blob/0cffaca4bda6d117d6e7356ee1017e25875d380d/Adafruit_BMP3XX.cpp#L354), there is a `delay(40)` for some reason. This delay would limit the reading to no more than 25Hz ... why? The sensor is capable of faster performance, not sure why you are hamstringing it like this ... maybe there is a more efficient way to do this?

Thanks again!

**Comment by ladyada** [comment]
pretty sure we got it from bosch's official self-test code :/
https://github.com/BoschSensortec/BMP3-Sensor-API/blob/master/self-test/bmp3_selftest.c#L153
do you wanna maybe ask them? on one hand i agree, there's no reason for it. on the other hand i find that its best to stick to the official example as much as possible since They May Know Things :D

**Comment by mjs513** [comment]
Just as a follow up to this - has there been any resolution.  

Reason.  I was testing on a Teensy 4.0 and getting a "Failed to perform reading :(" error.  I came across this and commented out the delay(40) and it magically started working.  Guess its time to read the manual.

**Comment by walchko** [comment]
Sorry no, not yet

**Comment by mjs513** [comment]
Thanks for the reply.  Just for reference I did try the sketch on the Uno, Due, Mega and a Teensy 3.5 with the delay(40) and it seemed to work with an issue.

**Comment by ladyada** [comment]
can someone please submit a PR? we'd review and merge!

**Comment by mjs513** [comment]
Thanks for incorporating the change.

**Comment by walchko** [comment]
Thanks @mjs513 ... I wasn't going to be able to get to this until tomorrow. I will close this now.

**Comment by ladyada** [comment]
thanks all!
