### ISSUE TITLE
Why do we have twice a function 

### ISSUE THREAD

**Issue by rvt** [adafruit/Adafruit_BMP3XX#17]
There are two functions with the same function signature:

https://github.com/adafruit/Adafruit_BMP3XX/blob/db2a5b4ec94db4ca8f8aa794f17f3c844c7f7981/bmp3.c#L2277
https://github.com/adafruit/Adafruit_BMP3XX/blob/db2a5b4ec94db4ca8f8aa794f17f3c844c7f7981/bmp3.c#L2416

Depending on the compile, one might be used over the other?

**Comment by ladyada** [comment]
look at 
`#ifdef BMP3_DOUBLE_PRECISION_COMPENSATION`
to understand it

**Comment by rvt** [comment]
Gotcha, I was not aware that these where just copied over...
