### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by simon88** [adafruit/Adafruit_BMP3XX#24]
Hi,

I'm trying to use this lib with an BMP384. During the `_init()` function I got an error when the lib try to `validate_trimming_param` I've tried to debug and the issue is in this line `if (stored_crc != crc) {` the sotred_crc is nerver egal to crc. I've tried to understand how to calculate crc etc but I didn't find any useful informaiton in the datasheet, however calibration data registers between BMP384 and BMP388 and addresses are the same.

**Comment by caternuson** [comment]
Closing. Question seems answered.
