### ISSUE TITLE
Pressure offset of around 7-8 mbar

### ISSUE THREAD

**Issue by muendlein** [adafruit/Adafruit_BMP3XX#26]
I have been using a BMP388 sensor to track the outdoor pressure. While doing that I have noticed that the sensor data is around 7-8 mbar lower compared to my local wheater station (see below).
As this offset is rather constant and cannot be explained by minor difference in altitudes or temperature I think that either the default temperature compensation of this library needs some tweaking or I am not using the settings properly. Of course I am open to other ideas/reasons that might explain the offset. Here are my settings:

```
  bmp.setTemperatureOversampling(BMP3_OVERSAMPLING_8X);  
  bmp.setPressureOversampling(BMP3_OVERSAMPLING_8X);
  bmp.setIIRFilterCoeff(BMP3_IIR_FILTER_DISABLE);
  bmp.setOutputDataRate(BMP3_ODR_12_5_HZ);
```

Apparently I am not only observing this: https://forum.arduino.cc/t/bmp388-pressure-sensor-is-giving-wrong-values/680641
In this forum thread a user also reported a delta of 7 mbar.

![measured_data_stretched](https://user-images.githubusercontent.com/71090451/220728772-9bccf32d-7731-4247-b4f0-ff157840b659.PNG)
![wheater_station](https://user-images.githubusercontent.com/71090451/220728777-050da258-5ae3-41a1-bd75-4bf5e325fbfc.PNG)

**Comment by caternuson** [comment]
```
As this offset is rather constant and cannot be explained by different minor altitudes
```
Why not? You are comparing to a sensor located at a different location.

**Comment by muendlein** [comment]
> ```
> As this offset is rather constant and cannot be explained by different minor altitudes
> ```
> 
> Why not? You are comparing to a sensor located at a different location.

The altitude delta is only around 10 meters and the locations are just a few kilometers apart.

**Comment by caternuson** [comment]
That's enough to account for a 7-8 mbar difference. Not just the elevation, but the actual location difference as well.
