### ISSUE TITLE
Software SPI not getting along with Hardware SPI

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BMP3XX#6]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=22&t=155128

BMP388 + SD breakout. Only work together if BMP uses HW SPI, but not SW SPI.

**Comment by ladyada** [comment]
yeah thats normal. you cant share SW SPI with HW SPI

**Comment by caternuson** [comment]
yah, that was it, nvm, thought this was on separate pins for some reason. closing.
