### ISSUE TITLE
Support BMP390 (BMP3-Sensor-API v2.0.1 now available)

### ISSUE THREAD

**Issue by niabassey** [adafruit/Adafruit_BMP3XX#8]
The upstream library has been updated to v2.0.1:
https://github.com/BoschSensortec/BMP3-Sensor-API

The update includes support for the BMP390 & BMP390L but renames and reorganizes several definitions, structs and functions.

**Comment by ladyada** [comment]
yep, check out https://github.com/adafruit/Adafruit_BMP3XX/pull/9 !

**Comment by niabassey** [comment]
I am testing with the BMP390L and it's working perfectly so far.
Thanks Limor!

**Comment by ladyada** [comment]
:)
